cask_args appdir: "/Applications"

tap "caskroom/cask"
tap "homebrew/bundle"
tap "homebrew/core"
tap "homebrew/dev-tools"
tap "homebrew/formula-analytics"
tap "homebrew/services"
tap "homebrew/test-bot"

cask "visual-studio-code"
cask "iterm2"
brew "icu4c"
brew "node"
brew "jpeg"
brew "readline"
brew "autoconf"
brew "openssl"
brew "cmake"
brew "git"
brew "grc"
brew "hub"
brew "imagemagick"
brew "ruby-build"
brew "rbenv"
brew "rbenv-default-gems"
brew "wget"
cask "spectacle"

cask "google-chrome"
cask "textexpander"
cask "textmate"
cask "vagrant"
cask "hipchat"

mas "1Password", id: 443987910
mas "Slack", id: 803453959
