[".asdf"]
    type = "git-repo"
    url = "https://github.com/asdf-vm/asdf.git"
    refreshPeriod = "168h"
    [".asdf".clone]
        args = ["--branch", "v0.14.0"]
[".nvm"]
    type = "git-repo"
    url = "https://github.com/nvm-sh/nvm.git"
    refreshPeriod = "168h"
    [".nvm".clone]
        args = ["--branch", "0.39.7"]
