# Schema for Chezmoi Data Configuration
# This file documents the structure of the data used in templates

# Core user information
data:
  # User details
  fullname: string                 # User's full name
  name: string                     # User's short name or first name
  username: string                 # Username for git and other services
  dotusername: string              # Alternative username format (e.g., john.doe)
  email: string                    # User's primary email

  # Editor preference
  editor: string                   # Default editor command (e.g., "code --wait")

  # Platform-specific configurations
  macos:
    terminal: string               # Terminal app on macOS (e.g., "iterm2")
  linux:
    terminal: string               # Terminal app on Linux (e.g., "ghostty")
  windows:
    terminal: string               # Terminal app on Windows (e.g., "windows-terminal")

  # Theme settings
  theme:
    name: string                   # Theme name (e.g., "github_dark")
    colors:
      accent: string               # Accent color hex code
      surface: string              # Background/surface color hex code
      text: string                 # Text color hex code

  # Tool version management
  versions:
    node: string                   # Node.js version (e.g., "lts")
    python: string                 # Python version (e.g., "3.11")
    go: string                     # Go version (e.g., "latest")
    rust: string                   # Rust version (e.g., "stable")

# Profile settings (optional, for supporting work/personal profiles)
profiles:
  # Work profile
  work:
    enabled: boolean               # Whether work profile is enabled
    email: string                  # Work email address
    additionalConfig: object       # Additional work-specific configurations

  # Personal profile
  personal:
    enabled: boolean               # Whether personal profile is enabled
    additionalConfig: object       # Additional personal-specific configurations

# Package management
packages:
  # Universal packages (installed on all environments)
  universal:
    taps: [string]                 # Homebrew taps
    brews: [string]                # Homebrew packages
    casks: [string]                # Homebrew casks
    mas: [object]                  # Mac App Store apps

  # Work-specific packages
  work:
    taps: [string]                 # Work-specific Homebrew taps
    brews: [string]                # Work-specific Homebrew packages
    casks: [string]                # Work-specific Homebrew casks
    mas: [object]                  # Work-specific Mac App Store apps

  # Personal-specific packages
  personal:
    taps: [string]                 # Personal-specific Homebrew taps
    brews: [string]                # Personal-specific Homebrew packages
    casks: [string]                # Personal-specific Homebrew casks
    mas: [object]                  # Personal-specific Mac App Store apps
