# ~/.config/starship.toml

scan_timeout = 10

[cmd_duration]
min_time          = 500
show_milliseconds = true

[git_commit]
commit_hash_length = 4
only_detached      = false

[env_var]
variable = "STARSHIP_SHELL"
default  = "unknown shell"
format   = "[$env_value]($style) "
